import '../globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`text-emerald-950 bg-emerald-50/30`}>
    <body>{children}</body>
    </html>
  )
}
