import '../globals.css'
import { AuthProvider } from '@/app/(frontend)/(auth)/components/providers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider api={'rest'}>
      <html lang="en">
      <body>{children}</body>
      </html>
    </AuthProvider>
  )
}
