import '../globals.css'
import Script from 'next/script'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <>
      {/*Start of HubSpot Embed Code*/}
      <Script type="text/javascript" id="hs-script-loader" async defer src={`//js.hs-scripts.com/${process.env.HS_PORTAL_ID}.js`} />
      {/*End of HubSpot Embed Code*/}
      <html lang="en">
      <body>{children}</body>
      </html>
    </>
  )
}
